//
// GameRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameRequest: Codable, JSONEncodable, Hashable {

    public enum Opponent: String, Codable, CaseIterable {
        case physical = "PHYSICAL"
        case mixed = "MIXED"
        case virtual = "VIRTUAL"
    }
    public var white: String
    public var black: String
    public var opponent: Opponent
    public var opponentStrength: Int

    public init(white: String, black: String, opponent: Opponent, opponentStrength: Int) {
        self.white = white
        self.black = black
        self.opponent = opponent
        self.opponentStrength = opponentStrength
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case white
        case black
        case opponent
        case opponentStrength
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(white, forKey: .white)
        try container.encode(black, forKey: .black)
        try container.encode(opponent, forKey: .opponent)
        try container.encode(opponentStrength, forKey: .opponentStrength)
    }
}

