//
// GameUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameUpdateRequest: Codable, JSONEncodable, Hashable {

    public enum Opponent: String, Codable, CaseIterable {
        case physical = "PHYSICAL"
        case mixed = "MIXED"
        case virtual = "VIRTUAL"
    }
    public var gameState: String?
    public var moves: [String]?
    public var white: String?
    public var black: String?
    public var checkers: [String]?
    public var opponent: Opponent?
    public var opponentStrength: Int?
    public var winner: String?

    public init(gameState: String? = nil, moves: [String]? = nil, white: String? = nil, black: String? = nil, checkers: [String]? = nil, opponent: Opponent? = nil, opponentStrength: Int? = nil, winner: String? = nil) {
        self.gameState = gameState
        self.moves = moves
        self.white = white
        self.black = black
        self.checkers = checkers
        self.opponent = opponent
        self.opponentStrength = opponentStrength
        self.winner = winner
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameState
        case moves
        case white
        case black
        case checkers
        case opponent
        case opponentStrength
        case winner
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gameState, forKey: .gameState)
        try container.encodeIfPresent(moves, forKey: .moves)
        try container.encodeIfPresent(white, forKey: .white)
        try container.encodeIfPresent(black, forKey: .black)
        try container.encodeIfPresent(checkers, forKey: .checkers)
        try container.encodeIfPresent(opponent, forKey: .opponent)
        try container.encodeIfPresent(opponentStrength, forKey: .opponentStrength)
        try container.encodeIfPresent(winner, forKey: .winner)
    }
}

