//
// GameResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GameResponse: Codable, JSONEncodable, Hashable {

    public enum Opponent: String, Codable, CaseIterable {
        case physical = "PHYSICAL"
        case mixed = "MIXED"
        case virtual = "VIRTUAL"
    }
    public var id: String
    public var gameState: String
    public var moves: [String]
    public var white: String
    public var black: String
    public var checkers: [String]
    public var opponentStrength: Int
    public var opponent: Opponent
    public var winner: String
    public var date: String

    public init(id: String, gameState: String, moves: [String], white: String, black: String, checkers: [String], opponentStrength: Int, opponent: Opponent, winner: String, date: String) {
        self.id = id
        self.gameState = gameState
        self.moves = moves
        self.white = white
        self.black = black
        self.checkers = checkers
        self.opponentStrength = opponentStrength
        self.opponent = opponent
        self.winner = winner
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case gameState
        case moves
        case white
        case black
        case checkers
        case opponentStrength
        case opponent
        case winner
        case date
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(gameState, forKey: .gameState)
        try container.encode(moves, forKey: .moves)
        try container.encode(white, forKey: .white)
        try container.encode(black, forKey: .black)
        try container.encode(checkers, forKey: .checkers)
        try container.encode(opponentStrength, forKey: .opponentStrength)
        try container.encode(opponent, forKey: .opponent)
        try container.encode(winner, forKey: .winner)
        try container.encode(date, forKey: .date)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GameResponse: Identifiable {}
