//
// MoveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MoveRequest: Codable, JSONEncodable, Hashable {

    public var move: String

    public init(move: String) {
        self.move = move
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case move
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(move, forKey: .move)
    }
}

