//
// MoveResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MoveResponse: Codable, JSONEncodable, Hashable {

    public var moveSucceeded: Bool
    public var newGameState: GameResponse

    public init(moveSucceeded: Bool, newGameState: GameResponse) {
        self.moveSucceeded = moveSucceeded
        self.newGameState = newGameState
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case moveSucceeded
        case newGameState
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(moveSucceeded, forKey: .moveSucceeded)
        try container.encode(newGameState, forKey: .newGameState)
    }
}

