//
// UserSessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserSessionResponse: Codable, JSONEncodable, Hashable {

    public var token: String
    public var CSRF: String
    public var validTo: String

    public init(token: String, CSRF: String, validTo: String) {
        self.token = token
        self.CSRF = CSRF
        self.validTo = validTo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case CSRF
        case validTo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(CSRF, forKey: .CSRF)
        try container.encode(validTo, forKey: .validTo)
    }
}

