//
// UserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var email: String
    public var password: String
    public var lastLogin: String
    public var activeSessions: [UserSessionResponse]
    public var role: String

    public init(id: String, email: String, password: String, lastLogin: String, activeSessions: [UserSessionResponse], role: String) {
        self.id = id
        self.email = email
        self.password = password
        self.lastLogin = lastLogin
        self.activeSessions = activeSessions
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case password
        case lastLogin
        case activeSessions
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encode(lastLogin, forKey: .lastLogin)
        try container.encode(activeSessions, forKey: .activeSessions)
        try container.encode(role, forKey: .role)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserResponse: Identifiable {}
