//
// UserLoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserLoginResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var email: String
    public var CSRF: String
    public var role: String

    public init(id: String, email: String, CSRF: String, role: String) {
        self.id = id
        self.email = email
        self.CSRF = CSRF
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case CSRF
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encode(CSRF, forKey: .CSRF)
        try container.encode(role, forKey: .role)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserLoginResponse: Identifiable {}
